# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

module Pangea
  module Resources
    module Tls
      include TlsCertRequest
      include TlsLocallySignedCert
      include TlsPrivateKey
      include TlsSelfSignedCert
    end
  end
end
