# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tls_self_signed_cert/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TlsSelfSignedCert
    include Pangea::Resources::ResourceBuilder

    define_resource :tls_self_signed_cert,
      attributes_class: Tls::Types::SelfSignedCertAttributes,
      outputs: { id: :id },
      map: [:allowed_uses, :private_key_pem, :validity_period_hours],
      map_present: [:dns_names, :ip_addresses, :subject, :uris]
  end
  module Tls
    include TlsSelfSignedCert
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tls)
