# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Tls::Types
  include Dry.Types()

  class SelfSignedCertAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Tls::Types

    attribute :allowed_uses, T::Array.of(T::String)
    attribute :private_key_pem, T::String
    attribute :validity_period_hours, T::Float
    attribute? :dns_names, T::Array.of(T::String).optional
    attribute? :ip_addresses, T::Array.of(T::String).optional
    attribute? :subject, T::Array.of(T::Hash).optional
    attribute? :uris, T::Array.of(T::String).optional
  end
end
