# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tls_locally_signed_cert/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TlsLocallySignedCert
    include Pangea::Resources::ResourceBuilder

    define_resource :tls_locally_signed_cert,
      attributes_class: Tls::Types::LocallySignedCertAttributes,
      outputs: { id: :id },
      map: [:allowed_uses, :ca_cert_pem, :ca_private_key_pem, :cert_request_pem, :validity_period_hours]
  end
  module Tls
    include TlsLocallySignedCert
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tls)
