# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Tls::Types
  include Dry.Types()

  class LocallySignedCertAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Tls::Types

    attribute :allowed_uses, T::Array.of(T::String)
    attribute :ca_cert_pem, T::String
    attribute :ca_private_key_pem, T::String
    attribute :cert_request_pem, T::String
    attribute :validity_period_hours, T::Float
  end
end
