# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tls_cert_request/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TlsCertRequest
    include Pangea::Resources::ResourceBuilder

    define_resource :tls_cert_request,
      attributes_class: Tls::Types::CertRequestAttributes,
      outputs: { id: :id },
      map: [:private_key_pem],
      map_present: [:dns_names, :ip_addresses, :subject, :uris]
  end
  module Tls
    include TlsCertRequest
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tls)
