# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

# Tls resources
require_relative 'pangea/resources/tls_cert_request/resource'
require_relative 'pangea/resources/tls_locally_signed_cert/resource'
require_relative 'pangea/resources/tls_private_key/resource'
require_relative 'pangea/resources/tls_self_signed_cert/resource'

# Tls module aggregator
require_relative 'pangea/resources/tls'
