# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tls_private_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TlsPrivateKey
    include Pangea::Resources::ResourceBuilder

    define_resource :tls_private_key,
      attributes_class: Tls::Types::PrivateKeyAttributes,
      outputs: { id: :id },
      map: [:algorithm]
  end
  module Tls
    include TlsPrivateKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tls)
