# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Tls::Types
  include Dry.Types()

  class PrivateKeyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Tls::Types

    attribute :algorithm, T::String
  end
end
