# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a tls_cert_request resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::TlsCertRequest do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { private_key_pem: 'test-value' } }

  describe ':tls_cert_request' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'tls_cert_request', 'test')
        validate_required_attributes(config, [:private_key_pem])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.tls_cert_request('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:tls_cert_request)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.tls_cert_request('test', required_attrs)

        expect(ref.id).to eq("${tls_cert_request.test.id}")
        expect(ref.cert_request_pem).to eq("${tls_cert_request.test.cert_request_pem}")
        expect(ref.key_algorithm).to eq("${tls_cert_request.test.key_algorithm}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'tls_cert_request', 'test')
        expect(config).not_to have_key('cert_request_pem')
        expect(config).not_to have_key('key_algorithm')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ dns_names: ['test-value'], ip_addresses: ['test-value'], subject: [{ 'key1' => 'val1' }], uris: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'tls_cert_request', 'full')
        expect(config).to have_key('dns_names')
        expect(config).to have_key('ip_addresses')
        expect(config).to have_key('subject')
        expect(config).to have_key('uris')
      end
    end

    context 'optional attributes' do
      it 'includes dns_names when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('opt', required_attrs.merge(dns_names: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'tls_cert_request', 'opt')
        expect(config).to have_key('dns_names')
      end

      it 'omits dns_names when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'tls_cert_request', 'minimal')
        expect(config).not_to have_key('dns_names')
      end
      it 'includes ip_addresses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('opt', required_attrs.merge(ip_addresses: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'tls_cert_request', 'opt')
        expect(config).to have_key('ip_addresses')
      end

      it 'omits ip_addresses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'tls_cert_request', 'minimal')
        expect(config).not_to have_key('ip_addresses')
      end
      it 'includes subject when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('opt', required_attrs.merge(subject: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'tls_cert_request', 'opt')
        expect(config).to have_key('subject')
      end

      it 'omits subject when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'tls_cert_request', 'minimal')
        expect(config).not_to have_key('subject')
      end
      it 'includes uris when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('opt', required_attrs.merge(uris: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'tls_cert_request', 'opt')
        expect(config).to have_key('uris')
      end

      it 'omits uris when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'tls_cert_request', 'minimal')
        expect(config).not_to have_key('uris')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:private_key_pem]
        expect(sensitive_fields).to include(:private_key_pem)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'tls_cert_request', 'typed')
        expect(config['private_key_pem']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_cert_request('first', required_attrs)
        synth.tls_cert_request('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'tls_cert_request')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :tls_cert_request,
    method: :tls_cert_request,
    required_attrs: { private_key_pem: 'test-value' },
    expected_outputs: [:id, :cert_request_pem, :key_algorithm],
    sensitive_fields: [:private_key_pem],
    immutable_fields: [],
    boolean_fields: []
end
