# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a tls_private_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::TlsPrivateKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { algorithm: 'test-value' } }

  describe ':tls_private_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_private_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'tls_private_key', 'test')
        validate_required_attributes(config, [:algorithm])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.tls_private_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:tls_private_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.tls_private_key('test', required_attrs)

        expect(ref.id).to eq("${tls_private_key.test.id}")
        expect(ref.ecdsa_curve).to eq("${tls_private_key.test.ecdsa_curve}")
        expect(ref.private_key_openssh).to eq("${tls_private_key.test.private_key_openssh}")
        expect(ref.private_key_pem).to eq("${tls_private_key.test.private_key_pem}")
        expect(ref.private_key_pem_pkcs8).to eq("${tls_private_key.test.private_key_pem_pkcs8}")
        expect(ref.public_key_fingerprint_md5).to eq("${tls_private_key.test.public_key_fingerprint_md5}")
        expect(ref.public_key_fingerprint_sha256).to eq("${tls_private_key.test.public_key_fingerprint_sha256}")
        expect(ref.public_key_openssh).to eq("${tls_private_key.test.public_key_openssh}")
        expect(ref.public_key_pem).to eq("${tls_private_key.test.public_key_pem}")
        expect(ref.rsa_bits).to eq("${tls_private_key.test.rsa_bits}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_private_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'tls_private_key', 'test')
        expect(config).not_to have_key('ecdsa_curve')
        expect(config).not_to have_key('private_key_openssh')
        expect(config).not_to have_key('private_key_pem')
        expect(config).not_to have_key('private_key_pem_pkcs8')
        expect(config).not_to have_key('public_key_fingerprint_md5')
        expect(config).not_to have_key('public_key_fingerprint_sha256')
        expect(config).not_to have_key('public_key_openssh')
        expect(config).not_to have_key('public_key_pem')
        expect(config).not_to have_key('rsa_bits')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:private_key_openssh, :private_key_pem, :private_key_pem_pkcs8]
        expect(sensitive_fields).to include(:private_key_openssh)
        expect(sensitive_fields).to include(:private_key_pem)
        expect(sensitive_fields).to include(:private_key_pem_pkcs8)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_private_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'tls_private_key', 'typed')
        expect(config['algorithm']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_private_key('first', required_attrs)
        synth.tls_private_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'tls_private_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :tls_private_key,
    method: :tls_private_key,
    required_attrs: { algorithm: 'test-value' },
    expected_outputs: [:id, :ecdsa_curve, :private_key_openssh, :private_key_pem, :private_key_pem_pkcs8, :public_key_fingerprint_md5, :public_key_fingerprint_sha256, :public_key_openssh, :public_key_pem, :rsa_bits],
    sensitive_fields: [:private_key_openssh, :private_key_pem, :private_key_pem_pkcs8],
    immutable_fields: [],
    boolean_fields: []
end
