# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a tls_locally_signed_cert resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::TlsLocallySignedCert do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { allowed_uses: ['test-value'], ca_cert_pem: 'test-value', ca_private_key_pem: 'test-value', cert_request_pem: 'test-value', validity_period_hours: 3.14 } }

  describe ':tls_locally_signed_cert' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_locally_signed_cert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'tls_locally_signed_cert', 'test')
        validate_required_attributes(config, [:allowed_uses, :ca_cert_pem, :ca_private_key_pem, :cert_request_pem, :validity_period_hours])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.tls_locally_signed_cert('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:tls_locally_signed_cert)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.tls_locally_signed_cert('test', required_attrs)

        expect(ref.id).to eq("${tls_locally_signed_cert.test.id}")
        expect(ref.ca_key_algorithm).to eq("${tls_locally_signed_cert.test.ca_key_algorithm}")
        expect(ref.cert_pem).to eq("${tls_locally_signed_cert.test.cert_pem}")
        expect(ref.early_renewal_hours).to eq("${tls_locally_signed_cert.test.early_renewal_hours}")
        expect(ref.is_ca_certificate).to eq("${tls_locally_signed_cert.test.is_ca_certificate}")
        expect(ref.max_path_length).to eq("${tls_locally_signed_cert.test.max_path_length}")
        expect(ref.ready_for_renewal).to eq("${tls_locally_signed_cert.test.ready_for_renewal}")
        expect(ref.set_subject_key_id).to eq("${tls_locally_signed_cert.test.set_subject_key_id}")
        expect(ref.validity_end_time).to eq("${tls_locally_signed_cert.test.validity_end_time}")
        expect(ref.validity_start_time).to eq("${tls_locally_signed_cert.test.validity_start_time}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_locally_signed_cert('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'tls_locally_signed_cert', 'test')
        expect(config).not_to have_key('ca_key_algorithm')
        expect(config).not_to have_key('cert_pem')
        expect(config).not_to have_key('early_renewal_hours')
        expect(config).not_to have_key('is_ca_certificate')
        expect(config).not_to have_key('max_path_length')
        expect(config).not_to have_key('ready_for_renewal')
        expect(config).not_to have_key('set_subject_key_id')
        expect(config).not_to have_key('validity_end_time')
        expect(config).not_to have_key('validity_start_time')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:ca_private_key_pem]
        expect(sensitive_fields).to include(:ca_private_key_pem)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_locally_signed_cert('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'tls_locally_signed_cert', 'typed')
        expect(config['allowed_uses']).to be_a(Array)
        expect(config['ca_cert_pem']).to be_a(String)
        expect(config['ca_private_key_pem']).to be_a(String)
        expect(config['cert_request_pem']).to be_a(String)
        expect(config['validity_period_hours']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.tls_locally_signed_cert('first', required_attrs)
        synth.tls_locally_signed_cert('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'tls_locally_signed_cert')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :tls_locally_signed_cert,
    method: :tls_locally_signed_cert,
    required_attrs: { allowed_uses: ['test-value'], ca_cert_pem: 'test-value', ca_private_key_pem: 'test-value', cert_request_pem: 'test-value', validity_period_hours: 3.14 },
    expected_outputs: [:id, :ca_key_algorithm, :cert_pem, :early_renewal_hours, :is_ca_certificate, :max_path_length, :ready_for_renewal, :set_subject_key_id, :validity_end_time, :validity_start_time],
    sensitive_fields: [:ca_private_key_pem],
    immutable_fields: [],
    boolean_fields: []
end
